version: "3.9"
services:
  api:
    build: ./infra/api
    volumes:
      - .:/app
    env_file:
      - .api.env
    ports:
      - "8080:8080"
  web:
    build:
      context: .
      dockerfile: infra/ui/Dockerfile
    volumes:
      - ./static:/app
      - ./.ui.env:/app/.env
    ports:
      - "4200:4200"
  memcached:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11211:11211'
